# Generated by Django 2.0.7 on 2018-12-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='work',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
