# Generated by Django 2.0.7 on 2018-12-23 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181223_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Userinfo',
            field=models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
