# Generated by Django 2.0.7 on 2019-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190118_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='code',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
