# Generated by Django 2.0.7 on 2018-09-09 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import productapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('aggree', models.IntegerField(default=0)),
                ('disagree', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_ratings', models.PositiveSmallIntegerField(default=0)),
                ('design_ratings', models.PositiveSmallIntegerField(default=0)),
                ('camera_ratings', models.PositiveSmallIntegerField(default=0)),
                ('sound_ratings', models.PositiveSmallIntegerField(default=0)),
                ('features_ratings', models.PositiveSmallIntegerField(default=0)),
                ('total_ratings', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[productapi.models.ToLowerCase])),
                ('image', models.ImageField(blank='False', upload_to='')),
                ('performance_ratings', models.IntegerField(default=0)),
                ('design_ratings', models.IntegerField(default=0)),
                ('camera_ratings', models.IntegerField(default=0)),
                ('sound_ratings', models.IntegerField(default=0)),
                ('features_ratings', models.IntegerField(default=0)),
                ('no_of_users', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='rated',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapi.Smartphone'),
        ),
        migrations.AddField(
            model_name='rated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='productapi.Smartphone'),
        ),
    ]
