# Generated by Django 2.0.7 on 2018-09-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rated',
            name='total_ratings',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
