# Generated by Django 2.0.7 on 2018-09-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0002_auto_20180910_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rated',
            name='total_ratings',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
