# Generated by Django 2.0.7 on 2018-09-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0005_auto_20180910_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='total_ratings',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
