# Generated by Django 2.0.7 on 2018-09-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0007_auto_20180911_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
        migrations.AddField(
            model_name='rated',
            name='issues_with_the_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rated',
            name='not_recommend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rated',
            name='overpriced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rated',
            name='recommend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='issues_with_the_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='not_recommend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='overpriced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='recommend',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
