# Generated by Django 2.0.7 on 2018-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0009_auto_20180911_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='rated',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
