# Generated by Django 2.0.7 on 2018-09-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0010_auto_20180911_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='commented',
            field=models.IntegerField(default=0),
        ),
    ]
