# Generated by Django 2.0.7 on 2018-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0011_smartphone_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='rated',
            name='has_commented',
            field=models.BooleanField(default=1),
        ),
    ]
