# Generated by Django 2.0.7 on 2018-09-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0012_rated_has_commented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rated',
            name='has_commented',
            field=models.BooleanField(default=0),
        ),
    ]
