# Generated by Django 2.0.7 on 2019-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0015_rated_has_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='written',
            field=models.IntegerField(default=0),
        ),
    ]
