# Generated by Django 2.0.7 on 2019-01-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0016_smartphone_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='rated',
            name='comment_dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rated',
            name='comment_like',
            field=models.IntegerField(default=0),
        ),
    ]
